chore: clean up for mock inputs

diff --git a/backend/.husky/pre-push b/backend/.husky/pre-push
--- a/backend/.husky/pre-push
+++ b/backend/.husky/pre-push
@@ -1,13 +1,13 @@
-    #!/bin/sh
-    . "$(dirname "$0")/_/husky.sh"
+  #!/bin/sh
+  . "$(dirname "$0")/_/husky.sh"
 
-    echo "Running tests before push..."
-    npm run test
+  echo "Running tests before push..."
+  npm run test
 
-    if [ $? -ne 0 ]; then
-      echo "Tests failed. Aborting push."
-      exit 1
-    fi
+  if [ $? -ne 0 ]; then
+    echo "Tests failed. Aborting push."
+    exit 1
+  fi
 
-    echo "Tests passed. Proceeding with push."
-    exit 0
+  echo "Tests passed. Proceeding with push."
+  exit 0
